### ISSUE TITLE
Delete this repo?

### ISSUE THREAD

**Issue by davidread** [okfn/ckanext-rdf#3]
I imagine OKF wants to promote https://github.com/ckan/ckanext-dcat over this stale old repo. Should this one be deleted in case people try and use it?

**Comment by akuckartz** [comment]
:+1:

**Comment by davidread** [comment]
@amercader do you agree?

**Comment by amercader** [comment]
@davidread I generally like to keep histories public in case they are needed in the future. I've pushed a commit removing the sources and clearly marked the repo as unmaintained: https://github.com/okfn/ckanext-rdf

Do you think that's enough?

**Comment by davidread** [comment]
That's great, thanks
